pipeline {
    agent {
        label 'android'
    }
    stages {
        stage('Build App') {
            steps {
                // Run the app
                 echo 'Building the App'
            }
        }
        stage('Tests') {
            steps {
                // run the tests
                echo 'Runing Tests'
            }
        }
        stage('Finished') {
            steps {
                //note when finished
                echo 'Finished building and testing'
            }
        }
    }
}
