pipeline {
    agent {
        label 'android'
    }
    stages {
        stage('Build App') {
            steps {
                // Run the app
                sh './gradlew SocialProjectSCE'
                archiveArtifacts '**/*.apk'
                archiveArtifacts artifacts: 'app/build/outputs/apk/*.apk', fingerprint: true
            }
        }
        stage('Tests') {
            steps {
                // run the tests
                sh './gradlew test'
            }
        }
        stage('Finished') {
            steps {
                //print finished
                echo 'Finished'
            }
        }
    }
}
