pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'maven:3-alpine'
                }
            }
        }
        stage('Tests') {
            steps {
                echo 'Building..'
            }
            agent {
                docker {
                    image 'maven:3-alpine'
                }
            }
         }
    }
}
